"""empty message

Revision ID: 261c004968a4
Revises: 8a0c9c00f04c
Create Date: 2023-01-03 17:58:35.801660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261c004968a4'
down_revision = '8a0c9c00f04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pw_reset_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pw_reset_request', schema=None) as batch_op:
        batch_op.drop_column('expires')

    # ### end Alembic commands ###
